### ISSUE TITLE
Type creation methods

### ISSUE THREAD

**Issue by REALDrummer** [asusoda/Corundum#18]
First, some small notes about this post:
  * When I put "random" in code, it's short for a random number in a range appropriate to the code sample.
  * When I say "instance class", I mean a class that represents an instance of a specific type as opposed to a type class, e.g. `ProjectileType`'s corresponding instance class would be `Projectile`.

I've been having trouble coming up with a good way to allow the creation of typed objects (like `Entities`) through types. For example, it's easy and convenient for plugin authors and for us to allow the creation of, say, a Wither Skeleton using `new WitherSkeleton()`, but then what if someone wants to create a new random `Mob`? It would be fantastic if they could just write `MobType.values()[random].create()`. (I already figured out that we can't do `new Mob(MobType.values()[random])`.) However, I'm having trouble finding a nice way to program this `create()` method in the A.P.I.

The way I see it, there are two options:

* We could use Java Reflection to use a type's name to find the class it corresponds to and call its constructor. However, this is problematic for many reasons:
    * Java Reflection means a performance hit. We could make our Java Reflection minimal here, but if someone makes, say, an arena plugin that may be handling arenas all over the server and spawning entities everywhere all over the place, this little performance hit could become a big issue.
   * There are really two ways to handle the type name -> instance class mapping that I can see and both have issues:
      * The classes could share their names exactly with the types, but that means that plugin authors couldn't extend them, which I know a lot of plugin authors like to do, especially for the `Player` class to add more properties and make their code easier.
      * There could be a method that returns the class that corresponds to that specific type, but then that's almost as much work as the second option below because we would have to implement that separately for each and every type.
   * Java Reflection complicates things quickly... in general.
   * If we implemented this method in `EntityType` and the other high-level types as expected, the return type of `create()` would have to be high-level, too, e.g. `Entity`. That means even if a plugin author uses a more specific type like `ProjectileType.values()[random].create()`, it would return an `Entity` type which would have to be casted to a `Projectile`. We could override the `ProjectileType.create()` to simply call `EntityType.create()` and cast the result to a `Projectile`, but then if we did this for all those types, we're not really saving that much work. In addition, the bottom-level types would still return their parent type, e.g. `ProjectileType.ARROW.create()` would return a `Projectile` rather than an `Arrow`; it would have to be casted. (Granted, I'm not sure why someone would use this this way when they could just use `new Arrow()`; I'm just pointing it out.)

* We could implement the `create()` method individually for each and every type available. We could write the `create()` methods into the bottom-level types (the types that actually call constructors instead of referring to a subtype) like this:
```
public static final NonLivingEntityType<?> ENDER_CRYSTAL = new NonLivingEntityType<>(200) {
    public EnderCrystal create() {
         return new EnderCrystal();
    }
};
```
This would be much easier on the computer and eliminate complexity code-wise and it would mean that the `create()` methods' return type could be specific without casting, but it would also mean a lot more code.

So, opinions on which option is better? Any ideas better than both of these? I'd love to hear them!

**Comment by Niadel** [comment]
It's a complicated setup indeed (seriously, not once have I ever seen a type with *3* generic parameters), but seeing as I understood the story of a game with an allegedly extremely complex and confusing story perfectly well, I should have no problem understanding this. Fortunately, this shouldn't concern the end plugin author, but as chances are there are going to be some versions of Corundum that implement mod compatibility, someone's going to have to understand it. However, the number of people doing this will probably be tiny. You probably might want to link that specification of the entity system in the docs for Corundum.

**Comment by REALDrummer** [comment]
@Niadel Yeah, it did get pretty darn complicated, but as you said, all the parameterization and other complicated stuff will be hidden from the plugin authors; all they'll have to know if they can use **instance classes** to get individual Entities, **type classes** to get an Entity's type, and **type enumeration interfaces** to get the different kinds of types. that seems pretty straightforward to me. The only part of that that might be slightly difficult is letting everyone know that they should ignore those generic type parameters and use raw types. We can put that in all the Javadocs and tutorial videos and all that, though.

We could give the **type enumeration interfaces** default visibility, but then we would have to have all those `Entity` classes in one big package. We could do that, and that's what Bukkit ended up doing with a lot of their stuff to hide things without getting too complicated. Still, there's no need for that any more since now those interfaces should be visible to plugin authors and I'm glad for that because having all those Entities -- or Items and Blocks as we'll have to do later -- in one package would just be ugly. Still, if we come across a similar problem later, your idea is one to keep in mind.

By the way, I haven't really figured out yet if it matters or not, but since `BlockType`s and `ItemType`s and `BiomeType`s and other types have equivalent Minecraft objects (unlike `EntityType`s), we may need a fourth type parameter for those classes for the type of Minecraft object they represent. We can figure that out when we come to it.

**Comment by REALDrummer** [comment]
I think this should help in understanding:

In Eclipse, you can make "templates" which allow you to use a keyword to create blocks of code with only a few pieces to fill in, which is really helpful because Java can be so redundant. I have two templates here that I'm using in my coding: one is for `Entity` classes: one is for *parent classes* and the other is for *base classes*. Remember that since **type classes** and **type enumeration interfaces** are both inside **instance classes**, these templates include all three.

If you want to use these in Eclipse, you can go to Window >> Preferences >> Java >> Editor >> Templates, create a new template, and plug this stuff into it. Ignore the "newName" things in some of the tags; that's just to tell Eclipse what it is that we're filling in.

For parent classes
====
For the *parent class* template, you only need to put in two things: the **instance class**'s name (`${class_name}`, which will also be used to name the **type class** and **type enumeration interface** by appending "Type" and "Types", respectively) and the Minecraft object class that best represents this type (`MC_type`).
```java
/** 
 * 
 * @param <S>
 *            is a self-parameterization; this type should be the same type as this class.
 * @param <MC>
 *            determines the type of Minecraft Entity <tt>Object</tt> that this class represents.
 * @param <T>
 *            determines the type of {@link EntityType} that represents the type of this class. */
public abstract class ${class_name:newName}<S extends ${class_name}<S, MC, T>, MC extends ${MC_type:newName}, T extends ${class_name}.${class_name}Type<T, MC, S>> extends ${parent_class}<S, MC, T> {
    protected ${class_name}(MC entityMC) {
        super(entityMC);
    }

    public static interface ${class_name}Types {
        // TODO
    }

    public abstract static class ${class_name}Type<S extends ${class_name}Type<S, MC, I>, MC extends ${MC_type}, I extends ${class_name}<I, MC, S>> extends ${parent_class}Type<S, MC, I> {
        protected ${class_name}Type(int id, int data) {
            super(id, data);

            addValueAs(${class_name}Type.class);
        }

        // abstract utilities

        // overridden utilities

        // pseudo-enum utilities
        @SuppressWarnings("rawtypes")
        public static ${class_name}Type getByID(int id) {
            return getByID(${class_name}Type.class, id);
        }

        @SuppressWarnings("rawtypes")
        public static ${class_name}Type getByID(int id, int data) {
            return getByID(${class_name}Type.class, id, data);
        }

        @SuppressWarnings("rawtypes")
        public static ${class_name}Type[] values() {
            return values(${class_name}Type.class);
        }
    }

    // type utilities

    // instance utilities
}
```
For base classes
====
*Base classes* take the same things as *parent classes* plus two more: the I.D. and data value of the object (`${id}` and `${data}` respectively; you can see them in the **type class** constructor).
```java
public class ${class_name:newName} extends ${parent_class:newName}<${class_name}, ${MC_type:newName}, ${class_name}.${class_name}Type> {
	public ${class_name}() {
		super(new ${MC_type}(null));
	}

    protected ${class_name}(${MC_type} entityMC) {
        super(entityMC);
    }

    protected static class ${class_name}Type extends ${parent_class}Type<${class_name}Type, ${MC_type}, ${class_name}> {
        public static final ${class_name}Type TYPE = new ${class_name}Type();

        private ${class_name}Type() {
            super(${id:newName}, ${data:newName});
        }

        // overridden utilities
    }

    // instance utilities

    // overridden utilities
    @Override
    public ${class_name}Type getType() {
        return ${class_name}Type.TYPE;
    }
}
```

**Comment by REALDrummer** [comment]
I have been busy on the `reengineering_Entities` branch... well, reengineering the Entities. Along the way, I noticed a couple problems or needs for certain things, so I had to make some changes to the templates for the *base* and *parent* classes. Most of them are minor; the important ones are adding `?` type parameters to type classes when they're used as return types (because apparently raw types are not the same as `?`-parameterized types) and adding the `fromMC()` method to allow us to much more easily get a Corundum Entity from a Minecraft Entity. I pasted the updated templates below.

Also, today is my first day back at school, so I won't have quite as much time to work on this, but I'll still keep going at it and dedicating as much time as I can.

For parent classes
===
```java
/** TODO
 * 
 * @param <S>
 *            is a self-parameterization; this type should be the same type as this class.
 * @param <MC>
 *            determines the type of Minecraft Entity <tt>Object</tt> that this class represents.
 * @param <T>
 *            determines the type of {@link EntityType} that represents the type of this class. */
public abstract class ${primary_type_name}<S extends ${primary_type_name}<S, MC, T>, MC extends ${MC_type:newName}, T extends ${primary_type_name}.${primary_type_name}Type<T, MC, S>> extends ${parent_class}<S, MC, T> {
    protected ${primary_type_name}(MC entityMC) {
        super(entityMC);
    }

    public static interface ${primary_type_name}Types {
        // TODO
    }

    public abstract static class ${primary_type_name}Type<S extends ${primary_type_name}Type<S, MC, I>, MC extends ${MC_type}, I extends ${primary_type_name}<I, MC, S>> extends ${parent_class}Type<S, MC, I> {
        protected ${primary_type_name}Type(int id, int data) {
            super(id, data);

            addValueAs(${primary_type_name}Type.class);
        }

        // abstract utilities

        // overridden utilities

        // pseudo-enum utilities
        public static ${primary_type_name}Type<?, ?, ?> getByID(int id) {
            return getByID(${primary_type_name}Type.class, id);
        }

        public static ${primary_type_name}Type<?, ?, ?> getByID(int id, int data) {
            return getByID(${primary_type_name}Type.class, id, data);
        }

        public static ${primary_type_name}Type<?, ?, ?>[] values() {
            return values(${primary_type_name}Type.class);
        }
    }

    // type utilities

    // instance utilities
}
```
For base classes
===
```java
public class ${primary_type_name} extends ${parent_class:newName}<${primary_type_name}, ${MC_type:newName}, ${primary_type_name}.${primary_type_name}Type> {
	public ${primary_type_name}() {
		super(new ${MC_type}(null));
	}

    protected ${primary_type_name}(${MC_type} entityMC) {
        super(entityMC);
    }

    protected static class ${primary_type_name}Type extends ${parent_class}Type<${primary_type_name}Type, ${MC_type}, ${primary_type_name}> {
        public static final ${primary_type_name}Type TYPE = new ${primary_type_name}Type();

        private ${primary_type_name}Type() {
            super(${id:newName}, ${data:newName});
        }

        // overridden utilities
		@Override
		public ${primary_type_name} create() {
			return new ${primary_type_name}();
		}

		@Override
        public ${primary_type_name} fromMC(${MC_type} entityMC) {
            return new ${primary_type_name}(entityMC);
        }
    }

    // instance utilities

    // overridden utilities
    @Override
    public ${primary_type_name}Type getType() {
        return ${primary_type_name}Type.TYPE;
    }
}
```

**Comment by REALDrummer** [comment]
I finished implementing Entities in this way. Since I haven't heard any criticisms or anything, I'm assuming this system is good with everyone and I'm closing this issue. If anyone wants to comment, feel free to reopen this issue.
